version: 2
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - libc6
    - libgcc-s1
    - libgfortran5
    - libglx0
    - libgomp1
    - libopengl0
    - libstdc++6
    - libx11-6
    - libxcursor1
    - graphviz
  jobs:
    post_install:
      - ln -s $(pwd)/suanPan-linux-openblas-no-avx/bin/suanPan.sh /home/docs/.asdf/shims/suanpan
      - suanpan -v
python:
  install:
    - method: pip
      path: .
