version: 2
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - libc6
    - libcairo2-dev
    - libffi-dev
    - libfreetype6-dev
    - libgcc-s1
    - libgfortran5
    - libglx0
    - libgomp1
    - libjpeg-dev
    - libopengl0
    - libpng-dev
    - libstdc++6
    - libx11-6
    - libxcursor1
    - libz-dev
    - pngquant
  jobs:
    post_install:
      - ln -s $(pwd)/suanPan-linux-openblas-no-avx/bin/suanPan.sh /home/docs/.asdf/shims/suanpan
      - suanpan -v
python:
  install:
    - method: pip
      path: .
