version: 2
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libc6
    - libgcc-s1
    - libgfortran5
    - libglx0
    - libgomp1
    - libopengl0
    - libstdc++6
    - libx11-6
    - libxcursor1
  jobs:
    post_system_dependencies:
      - wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/suanPan-linux-mkl-vtk.tar.gz
      - tar xf suanPan-linux-mkl-vtk.tar.gz
      - cd suanPan-linux-mkl-vtk/bin && ./suanPan.sh --create-link
      - export PATH=$PATH:$HOME/.local/bin
python:
  install:
    - method: pip
      path: .
