site_name: suanPan manual
site_author: Theodore Chang
copyright: Copyright © 2017-2022 Theodore Chang
repo_url: "https://github.com/TLCFEM/suanPan-manual"
theme:
  name: material
  features:
    - navigation.tabs
  favicon: suanPan.svg
  logo: suanPan.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Turn off the lights
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Turn on the lights
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - smarty
  - toc:
      permalink: true
  - mdx_truly_sane_lists
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter:
      execute: True
      ignore: ["**/ProcessNZSM.py"]
#  - with-pdf:
#      cover_subtitle: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
#      ordered_chapter_level: 3
#      output_path: pdf/suanPan-manual.pdf
#      author: Theodore Chang
#      copyright: Copyright © 2017-2022 Theodore Chang
