site_name: suanPan manual
site_author: Theodore Chang
copyright: Copyright © 2017-2025 Theodore Chang
repo_url: "https://github.com/TLCFEM/suanPan-manual"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
  favicon: suanPan.svg
  logo: suanPan.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Turn off the lights
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Turn on the lights
extra_css:
  - color_scheme.css
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
      auto_title: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike
plugins:
  - search
  - awesome-pages
  - overwrite_math
  - mkdocs-jupyter:
      kernel_name: python
      theme: dark
      execute: true
      include:
        - '*.ipynb'
      ignore:
        - docs/Example/Structural/Statics/thin-walled-section.ipynb
        - docs/Example/Structural/Statics/calibration-subloading.ipynb
        - docs/Example/Structural/Dynamics/integrating-preprocessing-with-python.ipynb
        - docs/Example/Structural/Dynamics/process-ground-motion.ipynb
  # - with-pdf:
  #     cover_subtitle: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
  #     ordered_chapter_level: 3
  #     output_path: pdf/suanPan-manual.pdf
  #     author: Theodore Chang
  #     copyright: Copyright © 2017-2025 Theodore Chang
