name: latest
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Dependency
        run: |
          sudo apt-get install doxygen graphviz -y
          pip install -e .
      - name: Publish
        run: |
          git pull
          mike deploy 3.2
          git config --global user.name "Theodore Chang"
          git config --global user.email "tlcfem@gmail.com"
          git push origin gh-pages
