name: latest
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
#      - run: wget -q https://github.com/TLCFEM/suanPan/releases/download/suanPan-v2.8/suanPan-2.8.0-1.x86_64.deb
#      - run: sudo apt-get install ./suanPan-2.8.0-1.x86_64.deb
      - run: sudo apt-get install doxygen
      - run: git fetch origin
      - run: pip install -e .
      - run: git config --global user.name "Theodore Chang"
      - run: git config --global user.email "tlcfem@gmail.com"
      - run: mike deploy 2.9
      - run: git push origin gh-pages
