name: latest
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump')"
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Dependency
        run: |
          sudo apt-get install doxygen graphviz -y
          pip install -e .
          sudo ln -s $(pwd)/suanPan-linux-openblas-no-avx/bin/suanPan.sh /usr/bin/suanpan
          suanpan -v
      - name: Publish
        run: |
          git fetch origin
          git config --global user.name "Theodore Chang"
          git config --global user.email "tlcfem@gmail.com"
          git pull
          sed -i 's/execute: False/execute: True/g' mkdocs.yml
          mike deploy 3.4
          git push origin gh-pages
