name: latest
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'Bump') }}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Dependency
        run: |
          sudo apt-get install doxygen graphviz pngquant
          pip install -e .
          rm $(pwd)/suanPan-linux-openblas-no-avx/bin/updater
          sudo ln -s $(pwd)/suanPan-linux-openblas-no-avx/bin/suanPan.sh /usr/bin/suanpan
          suanpan -v
      - name: Deploy
        if: ${{ github.event_name != 'push' }}
        run: |
          mkdocs build
      - name: Publish
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch origin
          git config --global user.name "Theodore Chang"
          git config --global user.email "tlcfem@gmail.com"
          git pull
          mike deploy 4.0
          git push origin gh-pages
