jobs:
  deploy:
    env:
      SP_VERSION: "4.2"
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v7
      - name: Setup
        uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: "3.12"
      - name: Publish
        run: |
          sudo apt-get install doxygen graphviz pngquant
          pip install -e .
          find $(pwd)/suanPan* -type f -path "*/bin/updater" -exec rm -f {} +
          sudo ln -s $(find $(pwd)/suanPan* -type f -name suanPan.sh | head -n1) /usr/bin/suanpan
          suanpan -v
          git fetch origin
          git config --global user.name "Theodore Chang"
          git config --global user.email "tlcfem@gmail.com"
          git pull
          mike deploy $SP_VERSION -u latest
          git push origin gh-pages
name: Stable
"on":
  push:
    branches:
      - master
permissions:
  contents: write
