name: stable
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Publish
        run: |
          sudo apt-get install doxygen graphviz pngquant
          pip install -e .
          find $(pwd)/suanPan* -type f -path "*/bin/updater" -exec rm -f {} +
          sudo ln -s $(find $(pwd)/suanPan* -type f -name suanPan.sh | head -n1) /usr/bin/suanpan
          suanpan -v
          git fetch origin
          git config --global user.name "Theodore Chang"
          git config --global user.email "tlcfem@gmail.com"
          git pull
          mike deploy 4.1 -u latest
          git push origin gh-pages
